# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_display_name', models.CharField(max_length=255)),
                ('sharing_with_other_owners', models.BooleanField(default=0)),
                ('sharing_start_date', models.DateField()),
                ('number_of_slot_units', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assets_User_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField()),
                ('position_in_rotation', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_activated', models.BooleanField()),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DurationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetTypes'),
        ),
        migrations.AddField(
            model_name='assets',
            name='owners',
            field=models.ManyToManyField(through='assets.Assets_User_Mapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='slot_duration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.DurationTypes'),
        ),
    ]
