# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_display_name', models.CharField(max_length=255)),
                ('sharing_with_other_owners', models.BooleanField(default=0)),
                ('sharing_start_date', models.DateField()),
                ('number_of_slot_units', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Assets_User_Mapping',
            new_name='Asset_User_Mapping',
        ),
        migrations.RenameModel(
            old_name='AssetTypes',
            new_name='AssetType',
        ),
        migrations.RenameModel(
            old_name='DurationTypes',
            new_name='DurationType',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='slot_duration_unit',
        ),
        migrations.AlterField(
            model_name='asset_user_mapping',
            name='asset_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owners',
            field=models.ManyToManyField(through='assets.Asset_User_Mapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='slot_duration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.DurationType'),
        ),
    ]
