# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20161011_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='owners',
            new_name='asset_users',
        ),
        migrations.AlterField(
            model_name='asset_user_mapping',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
