# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20161118_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_user_mapping',
            name='invited_by',
        ),
    ]
