# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_asset_user_mapping_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images'),
        ),
    ]
