# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
