# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 23:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_subject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Your Comment'),
        ),
    ]
