# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stripedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeDetails',
            new_name='StripeDetail',
        ),
    ]
