# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20161015_1519'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='asset_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
            preserve_default=False,
        ),
    ]
