# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
