# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20161011_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
