# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingdetail_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='date_denied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='date_pending',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
