# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20161124_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='date_pending',
        ),
    ]
